Traceback (most recent call last):
  File "C:\page\examples\widgetdemo\widgetdemo.py", line 1866, in <module>
    widgetdemo_support.main()
  File "C:\page\examples\widgetdemo\widgetdemo_support.py", line 59, in main
    _w1 = widgetdemo.Main(_top1)
  File "C:\page\examples\widgetdemo\widgetdemo.py", line 217, in __init__
    _img0 = tk.PhotoImage(file=photo_location)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 4093, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 4038, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "./images/check-nu.png": no such file or directory
